title: Gustavson Family<br>Post-Christmas Quiz 2017
markdown: redcarpet
highlighter: pygments
exclude:
    - libs
    - misc
    - public
    - tmp
    - README.md
    - Gemfile
    - Gemfile.lock
    - .git
    - .gitignore
    - tags*
    - config.ru
    - package.json
    - yarn.lock
    - index.js
    - node_modules
    - webpack.config.js
    - vendor
destination: ./public
year: 2017
